# simple docker-compose.yaml
# services:
#   web:
#     build: .
#     command: uvicorn combined_asgi:app --host 0.0.0.0 --port ${APP_PORT}
#     ports:
#       - "${APP_PORT}:${APP_PORT}"
#     env_file:
#       - .env
#     volumes:
#       - .:/app





# multi stage docker-compose.yaml
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
      target: production  
    command: uvicorn combined_asgi:app --host 0.0.0.0 --port ${APP_PORT:-8000}
    ports:
      - "${APP_PORT:-8000}:${APP_PORT:-8000}"
    env_file:
      - .env
    volumes:
      - .:/app
    environment:
      - PYTHONUNBUFFERED=1