services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
      target: production
    env_file:
      - .env
    environment:
      - PYTHONUNBUFFERED=1
      - DJANGO_SETTINGS_MODULE=core.settings
    volumes:
      - .:/app
      - staticfiles:/staticfiles
      - media:/app/media
    expose:
      - "8000"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s

  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./static:/static  # 
      - ./baza.db:/app/baza.db 
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - staticfiles:/staticfiles
      - media:/app/media
    # depends_on:
    #   web:
    #     condition: service_healthy

volumes:
  staticfiles:
  media:
